import { PieDataItem } from "@/components/dashboard/PieChartComponent";
import { TaskTableItem } from "@/components/dashboard/TaskTable";
import { LinkItem } from "@/components/layout/DashboardLayout";
import {
  LayoutDashboard,
  ListTodo,
  BarChart3,
  User,
  Settings,
} from "lucide-react";

export const myTasksData: TaskTableItem[] = [
  {
    id: "T-001",
    title: "Conduct ISO 9001 Audit for Access Bank",
    description:
      "Complete annual ISO 9001 certification audit documentation and site inspection",
    assignedBy: "David Adebayo",
    assignedTo: {
      name: "Aisha Bello",
      avatar: "AB",
    },
    dueDate: "2026-02-05",
    priority: "High",
    status: "In Progress",
    category: "Audit",
    progress: 65,
    startDate: "2026-01-15",
    estimatedHours: 40,
    hoursLogged: 26,
    tags: ["ISO", "Banking", "Compliance"],
    createdAt: "2026-01-15",
    // comments: 8,
    // attachments: 3,
  },
  {
    id: "T-002",
    title: "Update Risk Register QHSE",
    description:
      "Quarterly update of risk assessment documentation for all departments",
    assignedBy: "Sarah Johnson",
    assignedTo: {
      name: "John Tobi",
      avatar: "JT",
    },
    dueDate: "2026-02-10",
    priority: "Medium",
    status: "Not Started",
    category: "Documentation",
    progress: 0,
    startDate: "2026-01-20",
    estimatedHours: 16,
    hoursLogged: 0,
    tags: ["QHSE", "Risk Management"],
    createdAt: "2026-01-10",
    // comments: 2,
    // attachments: 1,
  },
  {
    id: "T-003",
    title: "Safety Training Session Prep",
    description:
      "Prepare materials and venue for monthly safety training workshop",
    assignedBy: "Michael Okoro",
    assignedTo: {
      name: "Chibuike Chinedu",
      avatar: "CC",
    },
    dueDate: "2026-01-30",
    priority: "High",
    status: "Completed",
    category: "Training",
    progress: 100,
    startDate: "2026-01-10",
    estimatedHours: 8,
    hoursLogged: 8.5,
    tags: ["Safety", "Training"],
    createdAt: "2026-02-1",
    // comments: 5,
    // attachments: 2,
  },
  {
    id: "T-004",
    title: "Client Report Submission",
    description: "Submit monthly compliance report to GT Bank management",
    assignedBy: "David Adebayo",
    assignedTo: {
      name: "Ifeanyi Iheme",
      avatar: "II",
    },
    dueDate: "2026-02-01",
    priority: "Medium",
    status: "Pending Review",
    category: "Reporting",
    progress: 90,
    startDate: "2026-01-18",
    estimatedHours: 12,
    hoursLogged: 11,
    tags: ["Reporting", "Banking"],
    createdAt: "2026-01-01",
    // comments: 12,
    // attachments: 5,
  },
  {
    id: "T-005",
    title: "Equipment Calibration",
    description: "Calibrate all testing equipment as per annual schedule",
    assignedBy: "Emmanuel Okafor",
    assignedTo: {
      name: "Odumeje Ndaboski",
      avatar: "ON",
    },
    dueDate: "2026-02-15",
    priority: "Low",
    status: "In Progress",
    category: "Maintenance",
    progress: 30,
    startDate: "2026-01-22",
    estimatedHours: 20,
    hoursLogged: 6,
    tags: ["Equipment", "Maintenance"],
    createdAt: "2026-01-15",
    // comments: 3,
    // attachments: 1,
  },
  {
    id: "T-006",
    title: "Environmental Impact Assessment",
    description: "Conduct EIA for new manufacturing facility project",
    assignedBy: "Grace Nwosu",
    assignedTo: {
      name: "Ifeanyi Iheme",
      avatar: "II",
    },
    dueDate: "2026-02-20",
    priority: "High",
    status: "In Progress",
    category: "Assessment",
    progress: 45,
    startDate: "2026-01-25",
    estimatedHours: 32,
    hoursLogged: 14.5,
    tags: ["Environment", "Assessment"],
    createdAt: "2026-01-25",
    // comments: 6,
    // attachments: 4,
  },
  {
    id: "T-001",
    title: "Conduct ISO 9001 Audit for Access Bank",
    description: "Complete annual ISO 9001 certification audit",
    assignedBy: "Adamu Isa",
    assignedTo: { name: "Aisha Bello", avatar: "AB" },
    dueDate: "2026-02-05",
    priority: "High",
    status: "In Progress",
    category: "Audit",
    progress: 65,
    startDate: "2026-01-25",
    estimatedHours: 32,
    hoursLogged: 14.5,
    tags: ["ISO", "Banking", "Compliance"],
    createdAt: "2026-01-15",
  },
  {
    id: "T-002",
    title: "Update Risk Register QHSE",
    description: "Quarterly update of risk assessment documentation",
    assignedBy: "Obi Peter",
    assignedTo: { name: "Michael Okoro", avatar: "MO" },
    dueDate: "2026-02-10",
    priority: "Medium",
    status: "Not Started",
    category: "Documentation",
    progress: 0,
    startDate: "2026-01-10",
    estimatedHours: 12,
    hoursLogged: 4.5,
    tags: ["QHSE", "Risk Management"],
    createdAt: "2026-01-20",
  },
  {
    id: "T-003",
    title: "Safety Training Session Prep",
    description: "Prepare materials for monthly safety training",
    assignedBy: "John Dumelo",
    assignedTo: { name: "Fatima Yusuf", avatar: "FY" },
    dueDate: "2026-01-30",
    priority: "High",
    status: "Completed",
    category: "Training",
    progress: 100,
    startDate: "2026-01-02",
    estimatedHours: 32,
    hoursLogged: 5,
    tags: ["Safety", "Training"],
    createdAt: "2026-01-10",
  },
  {
    id: "T-004",
    title: "Client Report Submission",
    description: "Submit monthly compliance report to GT Bank",
    assignedBy: "James Tom",
    assignedTo: { name: "David Adebayo", avatar: "DA" },
    dueDate: "2026-02-01",
    priority: "Medium",
    status: "Pending Review",
    category: "Reporting",
    progress: 90,
    startDate: "2026-01-25",
    estimatedHours: 32,
    hoursLogged: 14.5,
    tags: ["Reporting", "Banking"],
    createdAt: "2026-01-18",
  },
  {
    id: "T-005",
    title: "Equipment Calibration",
    description: "Calibrate testing equipment as per schedule",
    assignedBy: "Imole Tobi",
    assignedTo: { name: "Aisha Bello", avatar: "AB" },
    dueDate: "2026-02-15",
    priority: "Low",
    status: "In Progress",
    category: "Maintenance",
    progress: 30,
    startDate: "2026-01-25",
    estimatedHours: 32,
    hoursLogged: 14.5,
    tags: ["Equipment", "Maintenance"],
    createdAt: "2026-01-22",
  },
  {
    id: "T-006",
    title: "Environmental Impact Assessment",
    description: "Conduct EIA for new client project",
    assignedBy: "Amenu Tawo",
    assignedTo: { name: "Michael Okoro", avatar: "MO" },
    dueDate: "2026-02-20",
    priority: "High",
    status: "In Progress",
    category: "Assessment",
    progress: 45,
    startDate: "2026-01-25",
    estimatedHours: 32,
    hoursLogged: 14.5,
    createdAt: "2026-01-25",
    tags: ["Environment", "Assessment"],
  },
  {
    id: "T-007",
    title: "Update ISO Documentation",
    description: "Review and update ISO 14001 procedures",
    assignedBy: "Bertha Iheme",
    assignedTo: { name: "Fatima Yusuf", avatar: "FY" },
    dueDate: "2026-02-12",
    priority: "Medium",
    status: "Not Started",
    category: "Documentation",
    progress: 0,
    startDate: "2026-01-25",
    estimatedHours: 32,
    hoursLogged: 14.5,
    tags: ["ISO", "Documentation"],
    createdAt: "2026-01-26",
  },
  {
    id: "T-008",
    title: "Staff Performance Review",
    description: "Quarterly performance evaluation",
    assignedBy: "Gabriel William",
    assignedTo: { name: "David Adebayo", avatar: "DA" },
    dueDate: "2026-02-08",
    priority: "Medium",
    status: "In Progress",
    category: "HR",
    progress: 55,
    startDate: "2026-01-25",
    estimatedHours: 32,
    hoursLogged: 14.5,
    tags: ["HR", "Performance"],
    createdAt: "2026-01-12",
  },
];

export const myTaskStats = myTasksData.reduce(
  (acc, task) => {
    acc.total += 1;

    if (task.status === "In Progress") acc.inProgress += 1;
    if (task.status === "Completed") acc.completed += 1;
    if (task.status === "Not Started") acc.notStarted += 1;
    if (task.status === "Not Started") acc.notStarted += 1;
    if (task.status === "Pending Review") acc.pending += 1;

    // 👇 overdue logic inside reduce
    if (new Date(task.dueDate) < new Date() && task.status !== "Completed") {
      acc.overdue += 1;
    }

    return acc;
  },
  {
    total: 0,
    inProgress: 0,
    notStarted: 0,
    completed: 0,
    overdue: 0,
    pending: 0,
  },
);

export const pieData: PieDataItem[] = [
  { name: "Completed", value: 9, color: "#059669" }, // Emerald-600 (success)
  { name: "In Progress", value: 7, color: "#1e40af" }, // Blue-800 (active)
  { name: "Pending", value: 8, color: "#64748b" }, // Slate-500 (neutral / waiting)
  { name: "Overdue", value: 4, color: "#b91c1c" }, // Red-700 (serious, muted alert)
];

export const navItems: LinkItem[] = [
  {
    href: "/dashboard/employee",
    label: "Dashboard",
    icon: LayoutDashboard,
  },
  {
    href: "/dashboard/employee/mytask",
    label: "My Tasks",
    icon: ListTodo,
  },
  {
    href: "/dashboard/employee/overview",
    label: "Overview",
    icon: BarChart3,
  },
  {
    href: "/dashboard/employee/profile",
    label: "Profile",
    icon: User,
  },
  {
    href: "/dashboard/employee/settings",
    label: "Settings",
    icon: Settings,
  },
];
