import { PieDataItem } from "@/components/dashboard/PieChartComponent";
import { TaskTableItem } from "@/components/dashboard/TaskTable";
import { LinkItem } from "@/components/layout/DashboardLayout";
import {
  LayoutDashboard,
  ListTodo,
  FileBarChart,
  Users,
  Settings,
  Plus,
  User,
} from "lucide-react";

export type TaskProps = {
  id: string;
  title: string;
  description: string;
  assignedTo: {
    name: string;
    avatar: string;
  };
  dueDate: string;
  priority: "High" | "Medium" | "Low";
  status: "Not Started" | "In Progress" | "Pending Review" | "Completed";
  category:
    | "Audit"
    | "Documentation"
    | "Training"
    | "Reporting"
    | "Maintenance"
    | "Assessment"
    | "HR";
  progress: number;
  createdAt: string;
  tags: string[];
};

export const recentTasks: TaskTableItem[] = [
  {
    id: "T-001",
    title: "Conduct ISO 9001 Audit for Access Bank",
    description:
      "Complete annual ISO 9001 certification audit documentation and site inspection",
    assignedBy: "David Adebayo",
    assignedTo: {
      name: "Aisha Bello",
      avatar: "AB",
    },
    dueDate: "2026-02-05",
    priority: "High",
    status: "In Progress",
    category: "Audit",
    progress: 65,
    startDate: "2026-01-15",
    estimatedHours: 40,
    hoursLogged: 26,
    tags: ["ISO", "Banking", "Compliance"],
    createdAt: "2026-01-15",
    // comments: 8,
    // attachments: 3,
  },
  {
    id: "T-002",
    title: "Update Risk Register QHSE",
    description:
      "Quarterly update of risk assessment documentation for all departments",
    assignedBy: "Sarah Johnson",
    assignedTo: {
      name: "John Tobi",
      avatar: "JT",
    },
    dueDate: "2026-02-10",
    priority: "Medium",
    status: "Not Started",
    category: "Documentation",
    progress: 0,
    startDate: "2026-01-20",
    estimatedHours: 16,
    hoursLogged: 0,
    tags: ["QHSE", "Risk Management"],
    createdAt: "2026-01-10",
    // comments: 2,
    // attachments: 1,
  },
  {
    id: "T-003",
    title: "Safety Training Session Prep",
    description:
      "Prepare materials and venue for monthly safety training workshop",
    assignedBy: "Michael Okoro",
    assignedTo: {
      name: "Chibuike Chinedu",
      avatar: "CC",
    },
    dueDate: "2026-01-30",
    priority: "High",
    status: "Completed",
    category: "Training",
    progress: 100,
    startDate: "2026-01-10",
    estimatedHours: 8,
    hoursLogged: 8.5,
    tags: ["Safety", "Training"],
    createdAt: "2026-02-1",
    // comments: 5,
    // attachments: 2,
  },
  {
    id: "T-004",
    title: "Client Report Submission",
    description: "Submit monthly compliance report to GT Bank management",
    assignedBy: "David Adebayo",
    assignedTo: {
      name: "Ifeanyi Iheme",
      avatar: "II",
    },
    dueDate: "2026-02-01",
    priority: "Medium",
    status: "Pending Review",
    category: "Reporting",
    progress: 90,
    startDate: "2026-01-18",
    estimatedHours: 12,
    hoursLogged: 11,
    tags: ["Reporting", "Banking"],
    createdAt: "2026-01-01",
    // comments: 12,
    // attachments: 5,
  },
  {
    id: "T-005",
    title: "Equipment Calibration",
    description: "Calibrate all testing equipment as per annual schedule",
    assignedBy: "Emmanuel Okafor",
    assignedTo: {
      name: "Odumeje Ndaboski",
      avatar: "ON",
    },
    dueDate: "2026-02-15",
    priority: "Low",
    status: "In Progress",
    category: "Maintenance",
    progress: 30,
    startDate: "2026-01-22",
    estimatedHours: 20,
    hoursLogged: 6,
    tags: ["Equipment", "Maintenance"],
    createdAt: "2026-01-15",
    // comments: 3,
    // attachments: 1,
  },
  {
    id: "T-006",
    title: "Environmental Impact Assessment",
    description: "Conduct EIA for new manufacturing facility project",
    assignedBy: "Grace Nwosu",
    assignedTo: {
      name: "Ifeanyi Iheme",
      avatar: "II",
    },
    dueDate: "2026-02-20",
    priority: "High",
    status: "In Progress",
    category: "Assessment",
    progress: 45,
    startDate: "2026-01-25",
    estimatedHours: 32,
    hoursLogged: 14.5,
    tags: ["Environment", "Assessment"],
    createdAt: "2026-01-25",
    // comments: 6,
    // attachments: 4,
  },
  {
    id: "T-001",
    title: "Conduct ISO 9001 Audit for Access Bank",
    description: "Complete annual ISO 9001 certification audit",
    assignedBy: "Adamu Isa",
    assignedTo: { name: "Aisha Bello", avatar: "AB" },
    dueDate: "2026-02-05",
    priority: "High",
    status: "In Progress",
    category: "Audit",
    progress: 65,
    startDate: "2026-01-25",
    estimatedHours: 32,
    hoursLogged: 14.5,
    tags: ["ISO", "Banking", "Compliance"],
    createdAt: "2026-01-15",
  },
  {
    id: "T-002",
    title: "Update Risk Register QHSE",
    description: "Quarterly update of risk assessment documentation",
    assignedBy: "Obi Peter",
    assignedTo: { name: "Michael Okoro", avatar: "MO" },
    dueDate: "2026-02-10",
    priority: "Medium",
    status: "Not Started",
    category: "Documentation",
    progress: 0,
    startDate: "2026-01-10",
    estimatedHours: 12,
    hoursLogged: 4.5,
    tags: ["QHSE", "Risk Management"],
    createdAt: "2026-01-20",
  },
  {
    id: "T-003",
    title: "Safety Training Session Prep",
    description: "Prepare materials for monthly safety training",
    assignedBy: "John Dumelo",
    assignedTo: { name: "Fatima Yusuf", avatar: "FY" },
    dueDate: "2026-01-30",
    priority: "High",
    status: "Completed",
    category: "Training",
    progress: 100,
    startDate: "2026-01-02",
    estimatedHours: 32,
    hoursLogged: 5,
    tags: ["Safety", "Training"],
    createdAt: "2026-01-10",
  },
  {
    id: "T-004",
    title: "Client Report Submission",
    description: "Submit monthly compliance report to GT Bank",
    assignedBy: "James Tom",
    assignedTo: { name: "David Adebayo", avatar: "DA" },
    dueDate: "2026-02-01",
    priority: "Medium",
    status: "Pending Review",
    category: "Reporting",
    progress: 90,
    startDate: "2026-01-25",
    estimatedHours: 32,
    hoursLogged: 14.5,
    tags: ["Reporting", "Banking"],
    createdAt: "2026-01-18",
  },
  {
    id: "T-005",
    title: "Equipment Calibration",
    description: "Calibrate testing equipment as per schedule",
    assignedBy: "Imole Tobi",
    assignedTo: { name: "Aisha Bello", avatar: "AB" },
    dueDate: "2026-02-15",
    priority: "Low",
    status: "In Progress",
    category: "Maintenance",
    progress: 30,
    startDate: "2026-01-25",
    estimatedHours: 32,
    hoursLogged: 14.5,
    tags: ["Equipment", "Maintenance"],
    createdAt: "2026-01-22",
  },
  {
    id: "T-006",
    title: "Environmental Impact Assessment",
    description: "Conduct EIA for new client project",
    assignedBy: "Amenu Tawo",
    assignedTo: { name: "Michael Okoro", avatar: "MO" },
    dueDate: "2026-02-20",
    priority: "High",
    status: "In Progress",
    category: "Assessment",
    progress: 45,
    startDate: "2026-01-25",
    estimatedHours: 32,
    hoursLogged: 14.5,
    createdAt: "2026-01-25",
    tags: ["Environment", "Assessment"],
  },
  {
    id: "T-007",
    title: "Update ISO Documentation",
    description: "Review and update ISO 14001 procedures",
    assignedBy: "Bertha Iheme",
    assignedTo: { name: "Fatima Yusuf", avatar: "FY" },
    dueDate: "2026-02-12",
    priority: "Medium",
    status: "Not Started",
    category: "Documentation",
    progress: 0,
    startDate: "2026-01-25",
    estimatedHours: 32,
    hoursLogged: 14.5,
    tags: ["ISO", "Documentation"],
    createdAt: "2026-01-26",
  },
  {
    id: "T-008",
    title: "Staff Performance Review",
    description: "Quarterly performance evaluation",
    assignedBy: "Gabriel William",
    assignedTo: { name: "David Adebayo", avatar: "DA" },
    dueDate: "2026-02-08",
    priority: "Medium",
    status: "In Progress",
    category: "HR",
    progress: 55,
    startDate: "2026-01-25",
    estimatedHours: 32,
    hoursLogged: 14.5,
    tags: ["HR", "Performance"],
    createdAt: "2026-01-12",
  },
];

export const myTaskStats = recentTasks.reduce(
  (acc, task) => {
    acc.total += 1;

    if (task.status === "In Progress") acc.inProgress += 1;
    if (task.status === "Completed") acc.completed += 1;
    if (task.status === "Not Started") acc.notStarted += 1;
    if (task.status === "Not Started") acc.notStarted += 1;
    if (task.status === "Pending Review") acc.pending += 1;

    // 👇 overdue logic inside reduce
    if (new Date(task.dueDate) < new Date() && task.status !== "Completed") {
      acc.overdue += 1;
    }

    return acc;
  },
  {
    total: 0,
    inProgress: 0,
    notStarted: 0,
    completed: 0,
    overdue: 0,
    pending: 0,
  },
);

export const pieData: PieDataItem[] = [
  { name: "Completed", value: 184, color: "#059669" },
  { name: "In Progress", value: 43, color: "#1e40af" },
  { name: "Not Started", value: 20, color: "#64748b" },
];

export const links: LinkItem[] = [
  { href: "/dashboard/ceo", label: "Dashboard", icon: LayoutDashboard },
  { href: "/dashboard/ceo/tasks", label: "All Tasks", icon: ListTodo },
  { href: "/dashboard/ceo/create", label: "Create Task", icon: Plus },
  { href: "/dashboard/ceo/reports", label: "Reports", icon: FileBarChart },
  { href: "/dashboard/ceo/employees", label: "Employees", icon: Users },
  { href: "/dashboard/ceo/profile", label: "My Profile", icon: User },
  { href: "/dashboard/ceo/settings", label: "Settings", icon: Settings },
];

export const allEmployees = [
  {
    id: "EMP-001",
    name: "Aisha Bello",
    email: "aisha.bello@company.com",
    phone: "+234 801 234 5678",
    position: "Senior Quality Auditor",
    department: "Quality Assurance",
    location: "Lagos, Nigeria",
    status: "Active",
    joinDate: "2023-03-15",
    avatar: "AB",
    tasksAssigned: 12,
    tasksCompleted: 8,
    performanceRating: 4.5,
  },
  {
    id: "EMP-002",
    name: "Michael Okoro",
    email: "michael.okoro@company.com",
    phone: "+234 802 345 6789",
    position: "Environmental Consultant",
    department: "Environmental",
    location: "Port Harcourt, Nigeria",
    status: "Active",
    joinDate: "2022-11-20",
    avatar: "MO",
    tasksAssigned: 10,
    tasksCompleted: 7,
    performanceRating: 4.2,
  },
  {
    id: "EMP-003",
    name: "Fatima Yusuf",
    email: "fatima.yusuf@company.com",
    phone: "+234 803 456 7890",
    position: "Safety Officer",
    department: "Health & Safety",
    location: "Abuja, Nigeria",
    status: "Active",
    joinDate: "2023-01-10",
    avatar: "FY",
    tasksAssigned: 15,
    tasksCompleted: 12,
    performanceRating: 4.8,
  },
  {
    id: "EMP-004",
    name: "David Adebayo",
    email: "david.adebayo@company.com",
    phone: "+234 804 567 8901",
    position: "Compliance Manager",
    department: "Compliance",
    location: "Lagos, Nigeria",
    status: "Active",
    joinDate: "2021-08-05",
    avatar: "DA",
    tasksAssigned: 8,
    tasksCompleted: 6,
    performanceRating: 4.3,
  },
  {
    id: "EMP-005",
    name: "Sarah Johnson",
    email: "sarah.johnson@company.com",
    phone: "+234 805 678 9012",
    position: "Documentation Specialist",
    department: "Documentation",
    location: "Lagos, Nigeria",
    status: "Active",
    joinDate: "2023-05-18",
    avatar: "SJ",
    tasksAssigned: 9,
    tasksCompleted: 9,
    performanceRating: 5.0,
  },
  {
    id: "EMP-006",
    name: "Emmanuel Okafor",
    email: "emmanuel.okafor@company.com",
    phone: "+234 806 789 0123",
    position: "Risk Analyst",
    department: "Risk Management",
    location: "Abuja, Nigeria",
    status: "On Leave",
    joinDate: "2022-06-12",
    avatar: "EO",
    tasksAssigned: 5,
    tasksCompleted: 3,
    performanceRating: 4.0,
  },
  {
    id: "EMP-007",
    name: "Grace Nwosu",
    email: "grace.nwosu@company.com",
    phone: "+234 807 890 1234",
    position: "Training Coordinator",
    department: "Training",
    location: "Port Harcourt, Nigeria",
    status: "Active",
    joinDate: "2023-09-22",
    avatar: "GN",
    tasksAssigned: 11,
    tasksCompleted: 8,
    performanceRating: 4.6,
  },
  {
    id: "EMP-008",
    name: "Ibrahim Musa",
    email: "ibrahim.musa@company.com",
    phone: "+234 808 901 2345",
    position: "Equipment Technician",
    department: "Maintenance",
    location: "Kano, Nigeria",
    status: "Inactive",
    joinDate: "2020-04-30",
    avatar: "IM",
    tasksAssigned: 3,
    tasksCompleted: 2,
    performanceRating: 3.8,
  },
];
